source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-twitter-plugin'
gem 'jekyll-paginate'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-assets'
gem 'jekyll-seo-tag'
gem 'jekyll-tagging-related_posts'
gem 'buff'
gem 'kramdown'
gem 'rouge'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
